<div class="entry-content about-outer" itemprop="text">
    <br>
    <h2>Welcome to Beverly Cove!</h2>
    <p>This is just a hobby website I use to learn new software architectures, technologies, and techniques. If you have
    suggestions or want to see something different, feel free to suggest: <a href="mailto:tom@tom.org">tom@tom.org</a>
    </p>
    <ul>
        <li>Station hardware: $station.hardware</li>
        <li>Server uptime: $station.os_uptime</li>
        <li>WeeWX uptime: $station.uptime</li>
        <li>WeeWX version: $station.version</li>
    </ul>
</div>
